# Generated by Django 4.0.2 on 2022-03-04 13:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='count_interest',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 13, 29, 15, 793478, tzinfo=utc)),
        ),
    ]
