# Generated by Django 4.0.2 on 2022-02-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_information_balance_information_bool_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='information',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='information',
            name='dept',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='information',
            name='interest',
            field=models.FloatField(default=0),
        ),
    ]
