# Generated by Django 4.0.2 on 2022-02-18 19:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_information_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='information',
            name='birthday',
            field=models.DateTimeField(default=datetime.date(2022, 2, 19)),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('dept', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
                ('interest', models.FloatField(default=0)),
                ('bool', models.BooleanField(default=False)),
                ('current_balance', models.FloatField(default=0)),
                ('date', models.DateTimeField()),
                ('birthday', models.DateTimeField(default=datetime.date(2022, 2, 19))),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.namehistory')),
            ],
        ),
    ]
