# Generated by Django 4.0.2 on 2022-02-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_namehistory_alter_information_birthday_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='payment',
            field=models.FloatField(default=0),
        ),
    ]
