# Generated by Django 4.0.2 on 2022-02-21 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_history_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='birthday',
        ),
        migrations.AddField(
            model_name='history',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='information',
            name='birthday',
            field=models.DateTimeField(default=datetime.date(2004, 5, 11)),
        ),
    ]
