# Generated by Django 4.0.2 on 2022-02-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_history_birthday_history_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='paid_count',
            field=models.IntegerField(default=0),
        ),
    ]
