# Generated by Django 4.0.2 on 2022-02-21 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_history_paid_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='birthday',
            field=models.DateTimeField(default=datetime.date(2004, 5, 11)),
        ),
    ]
