# Generated by Django 4.0.2 on 2022-02-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_history_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='interest_bool',
            field=models.BooleanField(default=True),
        ),
    ]
