# Generated by Django 4.0.2 on 2022-02-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_information_count_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='count_interest',
            field=models.DateTimeField(),
        ),
    ]
