# Generated by Django 4.0.2 on 2022-02-23 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_information_count_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='count_interest',
            field=models.DateTimeField(default=datetime.date(2022, 2, 21)),
        ),
        migrations.AlterField(
            model_name='information',
            name='date',
            field=models.DateTimeField(default=datetime.date(2022, 2, 23)),
        ),
    ]
