# Generated by Django 4.0.2 on 2022-02-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_information_count_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='count_interest',
            field=models.DateTimeField(),
        ),
    ]
