# Generated by Django 4.0.2 on 2022-02-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_information_count_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='count_interest',
        ),
    ]
