# Generated by Django 4.0.2 on 2022-02-24 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_information_count_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='date',
            field=models.DateTimeField(default=datetime.date(2022, 2, 24)),
        ),
    ]
